# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 10:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='admin', help_text='50 characters max.', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.TextField(default='Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 17, 10, 20, 33, 241232, tzinfo=utc), verbose_name='Published on'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Post Title', help_text='200 characters max', max_length=200),
        ),
    ]
