# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 14:23
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160217_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=blog.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
